accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('profile/', views.profile, name='profile'),
    path('<str:uuid>/', views.account_info, name='account info'),
]

leave_management_uiet/urls.py
from . import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from home.views import home
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView
from authentication.views import CustomPasswordResetConfirmView

admin.site.site_header = "University Institute of Engg. & Technology"
admin.site.site_title = "Uiet"

urlpatterns = [
    path('', home, name='home'),
    path('applications/', include('applications.urls')),
    path('superadmin/', include('superadmin.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('account/', include('accounts.urls')),
    path('accounts/reset/<uidb64>/<token>/',
         CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/reset/done/', RedirectView.as_view(url="/auth/login/"),
         name='password_reset_complete'),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from utils.choices import FieldChoices
import uuid


def GenUUID():
    return uuid.uuid4().hex[:10]


class Account(models.Model):
    uuid = models.CharField(max_length=25, default=GenUUID,
                            editable=False, unique=True, primary_key=True)
    title = models.CharField(
        choices=FieldChoices.titleChoices(), max_length=25)
    name = models.CharField(blank=False, null=False, max_length=50)
    gender = models.CharField(
        choices=FieldChoices.genderChoices(), max_length=15)
    branch = models.CharField(
        choices=FieldChoices.branchChoices(), max_length=15)
    phone = models.CharField(max_length=10)
    designation = models.CharField(
        choices=FieldChoices.designationChoices(), max_length=15)
    user = models.OneToOneField(
        User, on_delete=models.SET_NULL, null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    activated = models.BooleanField(default=False)

    def __str__(self):
        return self.uuid

templates/forms/forgot_pass.html
{% load static %}

<head>
    <link href={% static 'images/logo.png' %} rel="icon" type="image/x-icon">
    <link rel="stylesheet" href={% static 'base.css' %}>
    <style>
        input {
            width: 340px !important;
            height: 50px !important;
            font-size: large;
        }
    </style>
</head>
{% include 'partitions/page_header.html' %}
<div class="apply-form">
    <form action="" method="post">
        {% csrf_token  %}
        <center>
            <h2>Reset Password</h2>

            <!-- fields -->
            <br>
            {{form.email}}
            <br>
            <br>
            <!------------------------------->

            <!-- error or success messages -->
            {% for field in form %}
            <strong class="alert"> {{ field.errors|striptags }}</strong>
            {% endfor %}

            {% if messages %}
            {% for message in messages %}
            <div class="alert">
                <strong>{{message}}</strong>
            </div>
            {% endfor %}
            {% endif %}
            <!------------------------------->

            <!-- form submit -->
            <br>
            <br>
            <button class="button save" type="submit">
                Reset
            </button>
            <!------------------------------->

        </center>
    </form>
</div>

templates/forms/leave_form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% block head %}
<link rel="stylesheet" href={% static 'leave_form.css' %}>
<title>Apply Leave | UIET</title>
{% endblock %}

{% include 'partitions/page_header.html' %}
<div class="apply-form">
    <form action="" method="post">
        {% csrf_token  %}
        <center>
            <h2>Leave form</h2>

            <!-- fields -->
            <div class="fields">
                <div class="_field">
                    <label>Type*</label>
                    <br>
                    {{form.type}}
                    {{form.type.errors}}
                </div>
                <!-- this field display only for non teaching staff -->
                {% if account.designation == 'Non-Teaching' %}
                <div class="_field">
                    <label>Time*</label>
                    <br>
                    {{form.time_period}}
                </div>
                {% endif %}
                <!-- ^^^ field display only for non teaching staff -->
            </div>
            {{form.reason}}
            <br>
            <br>
            <div class="fields">
                <div class="_field">
                    <label>Date from*</label>
                    <br>
                    {{form.date_from}}
                    {{form.type.errors}}
                </div>
                <div class="_field">
                    <label>Date to*</label>
                    <br>
                    {{form.date_to}}
                    {{form.type.errors}}
                </div>
            </div>
            {{form.station_leave}} check if want to apply for station leave?
            <br>
            <!------------------------------->

            <!-- error or success messages -->
            {% if messages %}
            {% for message in messages %}
            <div class="alert">
                <strong>{{message}}</strong>
            </div>
            {% endfor %}
            {% endif %}
            <!------------------------------->

            <!-- form submit -->
            <button class="button save" type="submit">
                Apply
            </button>
            <!------------------------------->

        </center>
    </form>
</div>
{% endblock %}

templates/forms/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login | Uiet</title>
    <link rel="stylesheet" href={% static 'base.css' %}>
    <link rel="stylesheet" href={% static 'auth.css' %}>
    <link href={% static 'images/logo.png' %} rel="icon" type="image/x-icon">

</head>

<body>

    <form method="post">
        {% csrf_token %}
        <img class="logo" src={% static 'logo.png' %} alt="logo" />
        <br>
        <br>
        <div style="text-align: left;">
            <b style="margin-left: 5px; color: rgb(69, 69, 69); font-size: small;">
                {{form.username.label}}
            </b>
            <br>
            {{form.username}}
            <br>
            <b style="margin-left: 5px; color: rgb(69, 69, 69); font-size: small;">
                {{form.password.label}}
            </b>
            <br>
            {{form.password}}
            <br>
        </div>
        <a href="/auth/forgot_password/">Forgotten password? </a>
        <br>
        <!-- error or success messages -->
        {% if messages %}
        {% for message in messages %}
        <div class="alert">
            <strong>{{message}}</strong>
        </div>
        {% endfor %}
        {% endif %}
        <input type="submit" class="button" value="Login" />
    </form>

</body>

</html>

templates/forms/new_pass_form.html
{% load static %}

<head>
    <style>
        button {
            background-color: #6c7ae0;
        }
    </style>
    <link href={% static 'images/logo.png' %} rel="icon" type="image/x-icon">
    <link rel="stylesheet" href={%static 'base.css' %}>
</head>
<div style="margin-top:300px;">
    {% if form %}
    <form method="post">
        {% csrf_token  %}
        <center>
            New password:{{form.new_password1}}
            <br>
            {% if form.new_password1.errors %}
            <div class="alert">
                <strong>{{form.new_password1.errors}}</strong>
            </div>
            {% endif %}

            Confirm password:{{form.new_password2}}
            <br>
            {% if form.new_password2.errors %}
            <div class="alert">
                <strong>{{form.new_password2.errors}}</strong>
            </div>
            {% endif %}
            <br>
            <button type="submit">Set Password</button>
        </center>
    </form>
    {% else %}
    <center>
        <h1>
            The link you followed has expired!
        </h1>
    </center>
    {% endif %}
</div>

templates/forms/register_form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


{% block head %}
<title>Register User | UIET</title>
<style>
    @media only screen and (min-width: 600px) {
        .register-form .form-fields {
            display: flex;
        }

        .register-form form {
            max-width: 38em;
            padding: 1em 1em 1em 1em;
            margin: 0em auto;
            margin-top: 30px;
            background-color: #fff;
            border-radius: 4.2px;
            box-shadow: 0px 3px 10px -2px rgba(0, 0, 0, 0.2);
        }

    }

    .register-form h4 {
        margin: 10px;
        color: orange;
        font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
    }

    .register-form form {
        margin-top: 30px;
    }

    .register-form .field {
        background-color: #fff;
        border: 1px solid gray;
    }

    .register-form input {
        color: rgb(60, 60, 60);
        width: 90%;
        padding: 2%;
    }

    .register-form #id_gender {
        width: 95%;
    }

    .register-form #id_branch {
        width: 95%;
    }

    .register-form #id_designation {
        width: 95%;
    }

    .register-form .err {
        color: rgb(247, 37, 0);
    }

    .register-form button {
        margin: 10px;
    }

    .register-form .save {
        background-color: #6c7ae0;
    }
</style>
{% endblock %}


{% include 'partitions/page_header.html' %}
<div class="register-form">
    <form action="" method="post">
        {% csrf_token  %}
        <h4>Personal</h4>
        <div class="form-fields">
            {{form.title}}
            {{form.name}}
        </div>
        <div class="form-fields">
            {{form.username}}
            {{form.password}}
        </div>
        <div class="form-fields">
            {{form.phone}}
            {{form.email}}
        </div>
        <div class="form-fields">
            {{form.gender}}
            {{form.branch}}
            {{form.designation}}
        </div>
        <h4>Leave Status</h4>
        {% for field in status_form %}
        <div class="form-fields">
            <input type="text" placeholder="Leave type" readonly value="{{field.leave_name}}">
            <input name="{{field.leave_name}}" id="id_{{field.name}}" type="number"
                placeholder="total no. of leaves {{field.leave_name}}" required>
        </div>
        {% endfor %}

        {% if messages %}
        <center>
            {% for message in messages %}
            <div class="alert">
                <strong>{{message}}</strong>
            </div>
            {% endfor %}
        </center>
        {% endif %}

        {% for field in form %}
        <label class=" err">{{ field.errors }}</label>
        {% endfor %}
        <center>
            <button class="button save" type="submit">
                Register
            </button>
        </center>
    </form>
</div>
{% endblock %}

templates/forms/reset_pass_form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
    button {
        background-color: #6c7ae0;
    }
</style>
<div>
    {% if form %}
    <form method="post">
        {% csrf_token  %}
        <center style="margin-top:50px;">
            New password:{{form.new_password1}}
            <br>
            {% if form.new_password1.errors %}
            <div class="alert">
                <strong>{{form.new_password1.errors}}</strong>
            </div>
            {% endif %}

            Confirm password:{{form.new_password2}}
            <br>
            {% if form.new_password2.errors %}
            <div class="alert">
                <strong>{{form.new_password2.errors}}</strong>
            </div>
            {% endif %}
            <br>
            <button type="submit">Set Password</button>
        </center>
    </form>
    {% else %}
    <center>
        <b>
            <h3 style="margin-top:10px;">
                Your password has already reset successfully !
            </h3>
        </b>
    </center>
    {% endif %}
</div>
{% endblock %}